export const CATEGORY_KEYWORD_MAP = {
  "data analyst": ["data analyst", "business analyst", "data analysis"],
  "data engineer": ["data engineer", "etl", "data pipeline"],
  "data scientist": ["data scientist", "machine learning", "deep learning"],
  "ai engineer": ["ai engineer", "artificial intelligence", "ml engineer"],
  "backend developer": ["backend", "node.js", "golang", "java", "laravel"],
  "frontend developer": ["frontend", "react", "vue", "angular"],
  "full stack developer": ["fullstack", "full stack"],
  "devops engineer": ["devops", "kubernetes", "docker", "ci cd"],
  "it support": ["it support", "helpdesk", "technical support"],
  "database administrator": ["database", "dba", "postgresql", "mysql"],
};

export const STOP_WORDS = new Set([
  // Indonesian
  "dan",
  "atau",
  "yang",
  "untuk",
  "dengan",
  "dari",
  "dalam",
  "pada",
  "adalah",
  "telah",
  "akan",
  "dapat",
  "serta",
  "juga",
  "oleh",
  "agar",
  "kami",
  "saya",
  "tim",
  "ini",
  "itu",
  "nya",
  "ber",
  "kan",
  "satu",
  "bertanggung",
  "jawab",
  "membantu",
  "melakukan",
  "mengembangkan",
  "memberikan",
  "berkolaborasi",
  "menyampaikan",
  "membuat",
  "mendukung",
  "mengelola",
  "menyusun",
  "meningkatkan",
  "memastikan",
  "proses",
  "seperti",
  "antara",
  "setiap",
  "sebagai",
  "berbagai",
  // English
  "the",
  "and",
  "for",
  "with",
  "from",
  "that",
  "this",
  "have",
  "has",
  "was",
  "are",
  "were",
  "been",
  "including",
  "through",
  "based",
  "using",
  "focused",
  "working",
  "worked",
  "develop",
  "manage",
  "support",
  "contribute",
  "ensure",
  "various",
  "between",
  "such",
  "each",
]);

export const SECTION_WEIGHTS = [
  {
    pattern:
      /^(daftar keahlian|top skills|skills|keahlian|kompetensi)\s*:?\s*$/i,
    weight: 3,
  },
  {
    pattern:
      /^(pengalaman kerja|experience|ringkasan profil|summary|sertifikasi|certifications)\s*:?\s*$/i,
    weight: 2,
  },
  {
    pattern: /^(pendidikan|education)\s*:?\s*$/i,
    weight: 1,
  },
  {
    pattern: /^(kontak|contact|languages|bahasa)\s*:?\s*$/i,
    weight: 0,
  },
];
